name: Run tests

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run tests
        run: php artisan test
    services:
          # mysql-service Label used to access the service container
          mysql:
            # Docker Hub image (also with version)
            image: mysql:5.7
            env:
              ## Accessing to Github secrets, where you can store your configuration
              MYSQL_ROOT_PASSWORD: Level123@
              MYSQL_DATABASE: akevas-api
            ## map the "external" 3306 port with the "internal" 3306
            ports:
              - 3306:3306
            # Set health checks to wait until mysql database has started (it takes some seconds to start)
            options: >-
              --health-cmd="mysqladmin ping"
              --health-interval=10s
              --health-timeout=5s
              --health-retries=3
